### ISSUE TITLE
Jsonrpsee gives TooManyRequest errors when used on jsonrpsee

### ISSUE THREAD

**Issue by godmodegalactus** [blockworks-foundation/solana#26]
After comparing jsonrpc with jsonrpsee we get following error:
"RpcError(RpcRequestError(\"cluster version query failed: HTTP status client error (429 Too Many Requests) for url (http://139.178.82.223:8899/)\"))"

Here is whole zip.

You can easily test it with the repo : 
https://github.com/blockworks-foundation/solana-rpc-testing

You can use scripts :

To test rpc varing the threads and launching tests :  [bench-rpc-by-threads.sh](https://github.com/blockworks-foundation/solana-rpc-testing/blob/main/bench-rpc-by-threads.sh)

To create plots : https://github.com/blockworks-foundation/solana-rpc-testing/blob/main/plot_data.py

You can find more about errors in json output files.

Jsonrpsee should perform better than normal rpc in all the cases.

[jsonrpsee_jsonrpc_comparison.zip](https://github.com/blockworks-foundation/solana/files/11491426/jsonrpsee_jsonrpc_comparison.zip)

**Comment by aniketfuryrocks** [comment]
Fixed
