### ISSUE TITLE
Implement confirmation stage by using RPC Client

### ISSUE THREAD

**Issue by godmodegalactus** [blockworks-foundation/solana#3]
Confirm the transaction sent by transaction sender stage by RPC client. This can be done by using confirm transaction method of the rpc client. 
Try to add multiple known RPC list and confirm on multiple RPC at same time.
Weigh out pros and cons for single rpc vs multiple rpc,
Create metrics of time take between transaction Sent and Confirmed.

This stage should be reliable and should be able to confirm multiple transaction at the same time.

**Comment by mschneider** [comment]
Let's focus on the single rpc use-case for now
