### ISSUE TITLE
Implement confirmation stage by processing blocks

### ISSUE THREAD

**Issue by godmodegalactus** [blockworks-foundation/solana#4]
Confirm the transaction sent by transaction sender stage by subscribing to event will be triggered when we get a new block.
Treat each block and find if the signature we are looking is block or not.
This stage should be reliable and should be able to confirm multiple transaction at the same time.

**Comment by mschneider** [comment]
https://github.com/godmodegalactus/mango_bencher

Check method confirmations_by_blocks here we confirm transactions by checking if the signature is in the block.
